server:
  private-key: | # PKCS#8
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIJi1JE7fq4xFZTXiOWvK9PDEDVIOgsF0dMF46BMgT9jY
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAe8QtuyTwO7YgDmZegsPpPPGuMZkjg6209OoArIOVOz0=
    -----END PUBLIC KEY-----
  version: "1.0"
  name: "DomTok"
  log-level: "INFO" # OPTIONS: TRACE, DEBUG, INFO(default), NOTICE, WARN, ERROR, FATAL
  intranet-url: "" # 网关地址

administrator:
  secret: "domtok-secret"
  password: "$2a$14$6sUXbvlFBBdkm75aeQXXae0k8yKhSFVVQzqRZJU.qDH4r1/LzB8v."

defaultUser:
  account: ""
  password: ""

snowflake:
  datacenter-id: 0

mysql:
  addr: 127.0.0.1:3306
  database: DomTok
  username: DomTok
  password: DomTok
  charset: utf8mb4

oss:
  endpoint: ""
  accessKey-id: ""
  accessKey-secret: ""
  bucketname: ""
  main-directory: DomTok

elasticsearch:
  addr: 127.0.0.1:9200
  host: 127.0.0.1

redis:
  addr: 127.0.0.1:6379
  password: DomTok

jaeger:
  addr: 127.0.0.1:6831

kafka:
  address: 127.0.0.1:9092
  network: tcp
  user: domtok
  password: domtok-password

volcengine:
  api-key: ""
  base-url: ""
  region: ""
  model: ""

upyun:
  bucket: "w2-domtok"
  operator: "penqee"
  password: ""
  token-secret: ""
  token-timeout: 60
  uss-domain: "http://w2-domtok.test.upcdn.net" # 测试域名
  download-domain: ""

rocketmq:
  brokerAddr: 127.0.0.1:10911 # 端口定义于 ../docker/docker=-compose.yml
  nameSrvAddr: 127.0.0.1:9876 # 同上
  accessKey: DomTok # 定义于 ./rocketmq/plain_acl.yml
  secretKey: DomTok # 同上

otel:
  collector-addr: 127.0.0.1:4317

services:
  template:
    name: template
    load-balance: false
    addr:
      - 127.0.0.1:10001

  gateway:
    name: gateway
    load-balance: false
    addr:
      - 0.0.0.0:20001

  user:
    name: user
    load-balance: false
    addr:
      - 0.0.0.0:20002

  order:
    name: order
    load-balance: false
    addr:
      - 0.0.0.0:20003

  commodity:
    name: commodity
    load-balance: false
    addr:
      - 0.0.0.0:20004

  payment:
    name: payment
    load-balance: false
    addr:
      - 0.0.0.0:20005

  cart:
    name: cart
    load-balance: false
    addr:
      - 0.0.0.0:20006

  assistant:
    name: assistant
    load-balance: false
    addr:
      - 0.0.0.0:20007
